[package]
name = "native"
version = "0.1.0"
edition = "2021"

[lib]
name = "native"
crate-type = ["cdylib"]

[dependencies]
pyo3       = { version = "0.23", features = ["extension-module"] }
fontdue    = "0.9"
flate2     = "1"
base64     = "0.22"
chrono     = { version = "0.4", default-features = false, features = ["std", "clock"] }
chrono-tz  = "0.10"

[profile.release]
opt-level     = 3
lto           = "thin"
codegen-units = 1
